[
[	colors.h
[
[						IBM COLOR DEFINES
[	
[	Sunday, February 22, 1987 at 02:31 p.m.
[	



%define	BLACK				0
%define	BLUE					1
%define	GREEN				2
%define	CYAN					3
%define	RED					4
%define	MAGENTA				5
%define	BROWN				6
%define	WHITE				7
%define	GREY					8
%define	GRAY					8
%define	LIGHT_BLUE			9
%define	LIGHT_GREEN			10
%define	LIGHT_CYAN			11
%define	LIGHT_RED				12
%define	LIGHT_MAGENTA			13
%define	YELLOW				14
%define	LIGHT_WHITE			15

