[
[	contrlrs.h
[	
[					STANDARD AGI KEY CONTROLLERS
[
[	Friday, May 15, 1987 at 0:47 a.m.
[



%define	cHelp				1	[	Function keys
%define	cSoundToggle			2
%define	cEchoLine				3
%define	cF4					4
%define	cSave				5
%define	cF6					6
%define	cRestore				7
%define	cF8					8
%define	cRestart				9
%define	cSpeed				10

%define	cStatus				11	[	Control keys
%define	cInitJoy				12
%define	cToggleMonitor			13
%define	cCancelLine			14

%define	cDebug				15	[	Alt keys
%define	cShowEgo				16
%define	cShowObj				17
%define	cShowMem				18
%define	cObjInfo				19
%define	cShowPriority			20
%define	cSkipTest				21
%define	cQuit				22

%define	cMenu				23	[	Menu stuff
%define	cDummy				24
%define	cAbout				25
%define	cCalculator			26
%define	cPuzzle				27
%define	cBodilyFunction		28
%define	cClock				29
%define	cPause				30
%define	cSpeedSlow			31
%define	cSpeedNormal			32
%define	cSpeedFast			33
%define	cSpeedFastest			34

%define	cInvNumbers			35	[	Debug stuff
%define	cXY					36
%define	cGimme				37

%define	cCrescendo			38	[	Tandy odds & ends.
%define	cDecrescendo			39

%define	cVersion				40
%define	cBoss				41

