[
[	lcl_temp.h
[
[	LEISURE SUIT LARRY IN THE LAND OF THE LOUNGE LIZARDS GAME DEFINITIONS
[
[	Wednesday, March 11, 1987 at 9:48 a.m.
[



[	The 30 locals are numbered 200 - 229.  The 26 dynamics are numbered
[230 - 255.  Every flag and var in this list is reset by every new room.



[	LOCAL FLAGS, for use in room logics.
%flag	lf0					200
%flag	lf1					201
%flag	lf2					202
%flag	lf3					203
%flag	lf4					204
%flag	lf5					205
%flag	lf6					206
%flag	lf7					207
%flag	lf8					208
%flag	lf9					209
%flag	lf10					210
%flag	lf11					211
%flag	lf12					212
%flag	lf13					213
%flag	lf14					214
%flag	lf15					215
%flag	lf16					216
%flag	lf17					217
%flag	lf18					218
%flag	lf19					219
%flag	lf20					220
%flag	lf21					221
%flag	lf22					222
%flag	lf23					223
%flag	lf24					224
%flag	lf25					225
%flag	lf26					226
%flag	lf27					227
%flag	lf28					228
%flag	lf29					229

[	TEMP FLAGS for use in dynamic logics.
%flag	df0					230
%flag	df1					231
%flag	df2					232
%flag	df3					233
%flag	df4					234
%flag	df5					235
%flag	df6					236
%flag	df7					237
%flag	df8					238
%flag	df9					239
%flag	df10					240
%flag	df11					241
%flag	df12					242
%flag	df13					243
%flag	df14					244
%flag	df15					245
%flag	df16					246
%flag	df17					247
%flag	df18					248
%flag	df19					249
%flag	df20					250
%flag	df21					251
%flag	df22					252
%flag	df23					253
%flag	df24					254
%flag	df25					255



[	LOCAL VARS for use in room logics.
%var		lv0					200
%var		lv1					201
%var		lv2					202
%var		lv3					203
%var		lv4					204
%var		lv5					205
%var		lv6					206
%var		lv7					207
%var		lv8					208
%var		lv9					209
%var		lv10					210
%var		lv11					211
%var		lv12					212
%var		lv13					213
%var		lv14					214
%var		lv15					215
%var		lv16					216
%var		lv17					217
%var		lv18					218
%var		lv19					219
%var		lv20					220
%var		lv21					221
%var		lv22					222
%var		lv23					223
%var		lv24					224
%var		lv25					225
%var		lv26					226
%var		lv27					227
%var		lv28					228
%var		lv29					229
					  

[	TEMP VARS for use in dynamic logics.
%var		dv0					230
%var		dv1					231
%var		dv2					232
%var		dv3					233
%var		dv4					234
%var		dv5					235
%var		dv6					236
%var		dv7					237
%var		dv8					238
%var		dv9					239
%var		dv10					240
%var		dv11					241
%var		dv12					242
%var		dv13					243
%var		dv14					244
%var		dv15					245
%var		dv16					246
%var		dv17					247
%var		dv18					248
%var		dv19					249
%var		dv20					250
%var		dv21					251
%var		dv22					252
%var		dv23					253
%var		dv24					254
%var		dv25					255
