[
[	iv_names.h
[
[ LEISURE SUIT LARRY IN THE LAND OF THE LOUNGE LIZARDS INVENTORY OBJECT NAMES
[
[	Thursday, May 14, 1987 at 1:20 p.m.
[



%define	Wallet			1
%define	BreathSpray		2
%define	PocketLint		3
%define	Watch			4
%define	Apple			5
%define	Ring				6
%define	Whiskey			7
%define	RemoteControl		8
%define	Rose				9
%define	Rubber			10
%define	UsedRubber		11
%define	Candy			12
%define	Doll				13
%define	DiscoPass			14
%define	PocketKnife		15
%define	Wine				16
%define	Magazine			17
%define	Hammer			18
%define	Pills			19
%define	Rope				20
