[
[	iv_views.h
[
[	LEISURE SUIT LARRY IN THE LAND OF THE LOUNGE LIZARDS INVENTORY VIEWS
[
[	Saturday, April 4, 1987 at 12:55 p.m.
[	Thursday, May 14, 1987 at 1:20 p.m.
[



%view	ivWallet				101
%view	ivBreathSpray			102
%view	ivPocketLint			103
%view	ivWatch				104
%view	ivApple				105
%view	ivRing				106
%view	ivWhiskey				107
%view	ivRemoteControl		108
%view	ivRose				109
%view	ivRubber				110
%view	ivUsedRubber			111
%view	ivCandy				112
%view	ivDoll				113
%view	ivDiscoPass			114
%view	ivPocketKnife			115
%view	ivWine				116
%view	ivMagazine			117
%view	ivHammer				118
%view	ivPills				119
%view	ivRope				120
