[messages for room 56 -- lgcBlackjack
[	"Leisure Suit Larry in the Land of the Lounge Lizards"
[	by Al Lowe



%message	1
"Bet is $%v226.00         You have $%v90.00"

%message	2
"Bet is $%v225.00         You have $%v90.00"

%message	3
"Bet is $%v255.00         You have $%v90.00"

%message	4
"Congratulations, you've broken the bank.
 This casino has a limit of $250.00 per person, and you've reached it.
 No more for you, Larry!"

%message	5
"Dealer=%v222   Player=%v223   Split=%v224   "

