[
[	slots.h
[
[	LEISURE SUIT LARRY IN THE LAND OF THE LOUNGE LIZARDS BLACKJACK HEADER
[
[	Thursday, March 5, 1987 at 10:49 a.m.
[



%object	aLights				1
%object	aWheel1				2
%object	aWheel2				3
%object	aWheel3				4
%object	aWinner				13	[	Animated objects.


%flag	readyToLeave			200
%flag	readyToPlay			201
%flag	pulledHandle			202
%flag	showOdds				203


%var		bet					200
%var		wheel1				201
%var		wheel2				202
%var		wheel3				203
%var		multiple				204
%var		winnings				205
%var		winnerCycles			206
%var		function				207
	#define	PAY_WINNER	1
	#define	UPDATE_STATUS	2
