[
[	views.h
[
[	LEISURE SUIT LARRY IN THE LAND OF THE LOUNGE LIZARDS VIEW DEFINITIONS
[
[	Monday, April 6, 1987 at 9:01 p.m.
[	Thursday, May 14, 1987 at 10:23 p.m.
[



[*************     VIEWS    ************]
%view	vEgo					 0
%view	vEgoCollapsing			 1
%view	vEgoUndressing			 2
%view	vEgoDrowning			 3
%view	vEgoDead				 4
%view	vEgoBreathSpray		 5
%view	vEgoOnRope			 6
%view	vEgoInHotTub			 7
%view	vEgoWearingTowel		 8
%view	vEgoSittingOnBed		 9
%view	vEgoLeavingDumpster		10
[	%view	11
%view	vEgoGettingBeaten		12
%view	vEgoDiscoing1			13
%view	vEgoFlingingFawn		14
%view	vEgoOnToilet			15
%view	vEgoWithHooker			16
%view	vEgoPushingElevator		17
%view	vEgoWithFawnRm41		18
[	%view	19
%view	vEgoFalling			20
%view	vEgoMissingGroin		21
%view	vEgoRoadKill			22
#define	ROAD_KILL			22

[	%view	23
%view	vEgoTiedOnBed			24
[	%view	25
%view	vEgoLeavingWindow		26
%view	vEgoIntoDumpster		27
%view	vEgoOnLadder			28
%view	vEgoDiscoing2			29
%view	vEgoSittingLounge		30
%view	vEgoSunrise			31
%view	vSunrise				32
%view	vSunriseBang			33
[	%view	vEgo		34
[	%view	vEgo		35
[	%view	vEgo		36
[	%view	vEgo		37
%view	vCreditNames4			38
%view	vCreditNames1			39
%view	vCreditNames2			40
%view	vCreditNames3			41
%view	vTitles				42
%view	vTitleDoll			43
%view	vTitleEgo				44
%view	vKen					45
[	%view	46
%view	vRm14Drunk			47
%view	vTransparentPixel		48
%view	vBartender			49
%view	vBarExterior			50	[	various lights, etc.
%view	vBarInterior			51
%view	vBarDoor				52
%view	vBarFlys				53	[	2 single cels + 1 girl loop
%view	vBarGreaser			54
%view	vPainting				55
%view	vPimpDoor				56
%view	vRm14Stuff			57
%view	vToiletDoor			58
%view	vToiletOverflowing		59
%view	vToiletFountain		60
%view	vRm16Door				61
%view	vPimp				62
%view	vPimpBlockingStairs		63
%view	vTVOn				64
%view	vHookerFace			65
%view	vHookerWindow			66
%view	vHooker				67
%view	vCandy				68
%view	vRing				69
[	%view	70
[	%view	71
%view	vAlleyStuff			72
%view	vMugger				73
%view	vMuggerAttacking		74
%view	vDog					75	[	if dog below ego
%view	vDogPissing			76
%view	vCop					77
%view	vFlasher				78
%view	vDogPissing2			79	[	if dog behind ego
%view	vTaxi				80
%view	vTaxiDriver			81
%view	vTaxiMeter			82
%view	vTaxiWindshieldMovie	83
[	%view	84
%view	vDeathCar				85
[	%view	86
[	%view	87
%view	vEgoAndFawnSitting	88
%view	vFawnFace			89
%view	vDiscoExterior			90
%view	vDiscoBouncer			91
[	%view	92
%view	v7_11Bum				93
%view	vDiscoCustomers		94
[	%view	95
[	%view	96
[	%view	97
%view	vFawn			98
%view	vFawnDancing		99
%view	vDiscoInterior			100

[Views 101 - 129 are "Show object" inventory views, defined in "IV_VIEWS.H"

%view	v7_11Exterior			130
[	%view	131
%view	v7_11Iranian			132
%view	v7_11Customers			133	[	4 heads
%view	v7_11Interior			134
%view	vMagazines			135
%view	vCasinoExterior		136
[	%view	137
%view	vCasinoManInBarrel		138
%view	vCasinoInterior		139
[	%view	140
%view	vCasinoPatrons			141
[	%view	142
[	%view	143
[	%view	144				
[	%view	145
%view	vMONOCardsShuffling		146
%view	vSlots				147
%view	vSlotsWinner			148
%view	vNonWinner			149
%view	vWinner				150
%view	vCardsShuffling		151
%view	vClubs				152
%view	vSpades				153
%view	vHearts				154
%view	vDiamonds				155
%view	vBlankCard			156
%view	vCardBack				157
%view	vLoungeComedian		158
%view	vLoungeDancers			159
[	%view	160
[	%view	161
%view	vLoungeCandles			162
%view	vDrummer				163
%view	vAshtray				164
%view	vElevator				165
#define	L_EMPTY			0
#define	L_FLOOR			1
#define	L_DOORS			2
#define	L_WITH_EGO		3

%view	vReceptionist			166
%view	vReceptionistFace		167
%view	vElevatorDoors			168
%view	vBedroomDoors			169
%view	vChapelExterior		170
%view 	vChapelInterior		171
%view	vChapelMinister		172
[	%view	173
%view	vElevatorNumbers		174
%view	vHoneymoonHallwayDoor	175
%view	vHoneymoonSuiteStuff	176
%view	vCloseupBubbles		177
%view	vFireworks			178
%view	vRm44ElevatorDoors		179
%view	vEveFace		180
%view	vEveInTub		181
%view	vEve			182
	#define	L_WALKING_RIGHT	0
	#define	L_SITTING_ON_BED	1
	#define	L_AFTER_SEX		2

%view	vHotTubBubbles			183
%view	vDollDeflating			184
%view	vWorkshopDeadEgo		185	[	death workshop views
%view	vWorkshopStuff			186
%view	vWorkshopScientist		187
%view	vWorkshopMen			188
%view	vWorkshopLogo			189
%view	vWorkshopDroid			190

